services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_USER_DB=${NEXT_PUBLIC_USER_DB}
      - NEXT_PUBLIC_HOST_DB=${NEXT_PUBLIC_HOST_DB}
      - NEXT_PUBLIC_DATABASE_DB=${NEXT_PUBLIC_DATABASE_DB}
      - NEXT_PUBLIC_PASSWORD_DB=${NEXT_PUBLIC_PASSWORD_DB}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
